title: Sense HAT advent calendar
hero_image: images/banner.png
description: Count down to Christmas with your Sense HAT
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "sense-hat, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
